org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.226
neo_version_range=[21,)
loader_version_range=[4,)

## Mod Properties
mod_id=endlock
mod_name=End Locker
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.vercte
mod_authors=Vercte
mod_description=lock the end
